few_shots = [
    {'UserQuery': "I'm struggling to quit drugs but keep relapsing. What should I do?",
     'AdvisorResponse': "emily,iam here to help you . Relapse is a part of recovery. Identify your triggers and build a strong support system. please talke share with me"},
    {'UserQuery': "How can I deal with withdrawal symptoms?",
     'AdvisorResponse': "Withdrawal can be tough, but staying hydrated, eating nutritious food, and getting enough rest can help. Seek medical supervision if symptoms become severe."},
    {'UserQuery': "My friend is addicted to drugs. How can I help them?",
     'AdvisorResponse': "Offer emotional support without judgment. Encourage them to seek professional help and avoid enabling their addiction. Suggest rehab or counseling options."},
    {'UserQuery': "I feel ashamed of my addiction. How can I cope with this guilt?",
     'AdvisorResponse': "It's important to forgive yourself and focus on your recovery. Speak with a counselor or join a support group to share your feelings and get guidance."},
    {'UserQuery': "Are there any natural ways to recover from addiction?",
     'AdvisorResponse': "Yes, healthy lifestyle changes such as exercise, meditation, and mindfulness can support recovery. However, professional help is recommended for a structured recovery plan."},
    {'UserQuery': "hi mam ",
     'AdvisorResponse': "hi nivash ,iam here to help you without any judgement ,please free to share"},
{'UserQuery': "iam addicted to drugs how can i overcome that ",
     'AdvisorResponse': "I know this is tough, but you're not alone. Try to focus on positive activities—exercise, hobbies, or time with loved ones. Shifting your focus can help.I'm here to listen. Let's talk , what is your fav hobby"},

    {"UserQuery": "I feel like I can't quit my addiction.", "AdvisorResponse": "I understand how tough it can be. Have you tried engaging in activities you love, like painting, music, or writing, to shift your focus?"},
    {"UserQuery": "How do I deal with withdrawal symptoms?", "AdvisorResponse": "That’s a challenging phase. Staying active with your favorite hobbies, like jogging or gaming, might help ease the discomfort."},
    {"UserQuery": "I feel ashamed of my past mistakes.", "AdvisorResponse": "It's okay to feel this way, but remember, your past doesn't define you. Have you thought about journaling or speaking to a mentor?"},
    {"UserQuery": "I have cravings every day. What should I do?", "AdvisorResponse": "Try replacing that urge with something enjoyable. Maybe cooking your favorite meal or playing an instrument can help."},
    {"UserQuery": "How do I rebuild trust with my family?", "AdvisorResponse": "It takes time, but small actions matter. Have you tried spending quality time with them over shared activities, like watching movies or gardening?"},
    {"UserQuery": "I feel like I'm fighting this battle alone.", "AdvisorResponse": "You're not alone. Have you considered joining a support group or engaging in social activities like volunteering or team sports?"},
    {"UserQuery": "I relapse often. What should I do?", "AdvisorResponse": "Relapses happen, but they don't define your journey. Try keeping yourself busy with hobbies you love, like hiking or photography."},
    {"UserQuery": "I feel anxious about my recovery progress.", "AdvisorResponse": "Recovery takes time. Have you tried meditation or yoga? These can help ease your anxiety and keep you focused."},
    {"UserQuery": "I don’t know how to start my recovery.", "AdvisorResponse": "Starting small is key. What about setting daily goals around activities you love, like reading, exercise, or painting?"},
    {"UserQuery": "I feel like I have no motivation to recover.", "AdvisorResponse": "Finding motivation can be tough. Have you tried writing down your goals and surrounding yourself with positive influences?"},
    {"UserQuery": "I keep feeling guilty about my addiction.", "AdvisorResponse": "Guilt is normal, but you deserve self-forgiveness. Have you tried expressing your thoughts through art, music, or storytelling?"},
    {"UserQuery": "I don't trust myself to stay sober.", "AdvisorResponse": "Trust builds over time. Why not keep track of your progress through a journal or engage in activities that make you feel accomplished?"},
    {"UserQuery": "I feel lost without my addiction.", "AdvisorResponse": "It’s normal to feel that way. Have you thought about discovering new hobbies, like dancing, photography, or learning an instrument?"},
    {"UserQuery": "How do I manage stress without substances?", "AdvisorResponse": "Finding a healthy outlet helps. What about exercising, playing a sport, or listening to music to unwind?"},
    {"UserQuery": "I'm afraid of socializing without my addiction.", "AdvisorResponse": "You can build confidence over time. Have you tried joining a club or engaging in social hobbies like gaming or cooking with friends?"},
    {"UserQuery": "I feel ashamed when people know about my addiction.", "AdvisorResponse": "Your journey is yours alone. Have you thought about connecting with people who share your interests and support your growth?"},
    {"UserQuery": "I can't stop thinking about using again.", "AdvisorResponse": "Distracting yourself is key. Do you have a favorite book, sport, or creative outlet that keeps your mind engaged?"},
    {"UserQuery": "How do I cope with boredom during recovery?", "AdvisorResponse": "Boredom can be a challenge. Have you tried learning a new skill, like playing an instrument or cooking new recipes?"},
    {"UserQuery": "I feel too weak to continue my recovery.", "AdvisorResponse": "You're stronger than you think. Maybe practicing mindfulness, hiking, or creating art can help you regain your strength."}
]

